### ISSUE TITLE
Export not Collecting metric lbvserver

### ISSUE THREAD

**Issue by estefancaique** [citrix/citrix-adc-metrics-exporter#16]
After configuring netscaler-metrics-exporter it is not returning VPX lbvserver

**Comment by estefancaique** [comment]
What message is this that appears in the log

2019-09-04T20:45:26+0000 INFO     metrices for lbvserver with k8sprefix "VIP" are not fetched

**Comment by aroraharsh23** [comment]
Can you confirm the environment you are running this VPX with i meant the whether the exporter is run as :
script/docker/k8s setup/k8s with CIC.
This message is for the case when the exporter is run with Citrix ingress controller in k8s environment, there you need to provide the prefix used by CIC(will update the details in READMe). 
For now, check exporter help for that.
If you are not in CIC setup then, we can debug the issue.

**Comment by aroraharsh23** [comment]
We have updated the repo name and image directory, for any further testing please confirm on 
quay.io/citrix/citrix-adc-metrics-exporter:1.1 
or the new "exporter.py" script. Thanks.

**Comment by marcoapvilhena** [comment]
@aroraharsh23 we aren't using VPX as ingress controller. Our VPX is used only for Load Balance for non Kubernetes applications.

**Comment by aroraharsh23** [comment]
@marcoapvilhena Thanks for confirming, You can try with the updated script or container image, and let us know, if the issue stills persists or not.
quay.io/citrix/citrix-adc-metrics-exporter:1.1

**Comment by marcoapvilhena** [comment]
@aroraharsh23 We got the test after your update but we had the same issue. We found "metrices for lbvserver with k8sCICprefix "VIP" are not fetched" in the log

**Comment by aroraharsh23** [comment]
@marcoapvilhena Thanks for testing.
Just to clarify again, you are not running exporter as a pod as you mentioned, then, this log should not appear as it's placed under "KUBERNETES_SERVICE_HOST" environment variable. Is this variable set by any chance in your case? That should not be the case in of non-k8s.
Or you can try deleting the docker image/script and pulling it again, which i am suspecting is still the previous one.

**Comment by HatBeardZero** [comment]
I have the same issue running it as a cron/nohup setup.

2019-09-11T18:39:37+0000 INFO     metrices for lbvserver with k8sprefix "redacted" are not fetched

**Comment by marcoapvilhena** [comment]
@aroraharsh23 we are running this exporter as a pod, but our VPX doesn't work as ingress, only to balancing for non-kubernetes aplication.

The "KUBERNETES_SERVICE_HOST" variable is not setted. Bellow has the pod describe:

Name:               netscaler-metrics-exporter
Namespace:          monitoring
Priority:           0
PriorityClassName:  <none>
Node:               xxxxxx/xxxxx
Start Time:         Thu, 05 Sep 2019 11:40:59 -0300
Labels:             app=exporter
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"exporter"},"name":"netscaler-metrics-exporter","namespace":"...
                    kubernetes.io/psp: grafana-test
Status:             Running
IP:                 xxxxxxx
Containers:
  exporter:
    Container ID:  containerd://5092e68bddbc0c759f14e8fe9d83432b7081799b27024638f5c658cf98add040
    Image:         quay.io/citrix/citrix-adc-metrics-exporter:1.1
    Image ID:      sha256:b4343090e213bc85844bb29c8024b9bda741c4f65c99464292a97825687c0819
    Port:          <none>
    Host Port:     <none>
    Args:
      --target-nsip=xxxxxx:80
      --port=8888
      --username=root
      --password=xxxxxx
    State:          Running
      Started:      Thu, 05 Sep 2019 11:41:08 -0300
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lnvbq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-lnvbq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lnvbq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 600s
                 node.kubernetes.io/unreachable:NoExecute for 600s
Events:          <none>

**Comment by aroraharsh23** [comment]
@marcoapvilhena Looks like that we misunderstood your deployment. So, it's a pod after all But non-CIC.
In that case, that was a known issue, which we have fixed in 1.2, please update the same:
"quay.io/citrix/citrix-adc-metrics-exporter:1.2"

**Comment by marcoapvilhena** [comment]
@aroraharsh23 now is working fine. Thank you for help!!

**Comment by aroraharsh23** [comment]
@marcoapvilhena Thanks for confirming, closing the issue.
