### ISSUE TITLE
Typo in metrics.json

### ISSUE THREAD

**Issue by saruter** [citrix/citrix-adc-metrics-exporter#20]
**Describe the bug**
There is a typo in metrics.json:
` ["sslcryptoutilizationstat", "citrixadc_ssl_crypto_untilization_stat"], `
I think it should be `citrixadc_ssl_crypto_utilization_stat`

**Comment by aroraharsh23** [comment]
Thanks for reporting this typo. I have corrected the same in metrics.json. Will incorporate this in next release.
