### ISSUE TITLE
Typo in metrics.json

### ISSUE THREAD

**Issue by manuchauvet** [citrix/citrix-adc-metrics-exporter#21]
There is a typo in metrics.json :
["avgcltttlb", "citrixadc_lb_avergage_ttlb"] should be ["avgcltttlb", "citrixadc_lb_average_ttlb"] I guess

**Comment by aroraharsh23** [comment]
Thanks for reporting this Typo. I have corrected this and some others in metrics.json. Will include in the next release image.
