### ISSUE TITLE
urllib3 is not part of requests anymore

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/citrix-adc-metrics-exporter#31]
**Describe the bug**
pip install requests will install latest version of the lib
this doesn't work on latest version of the requests lib:
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

This logs fills up the FS in days.

**To Reproduce**
1. Use any ADC with self signed cert
2. Latest as today
3. Any
4. Log:
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host

**Expected behavior**
No log.

**Probable solution**
Something in the lines of:
Lines to remove:
-from requests.packages.urllib3.exceptions import InsecureRequestWarning
-requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
-requests.packages.urllib3.disable_warnings(SubjectAltNameWarning)

Lines to add in the proper place:
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
urllib3.disable_warnings(urllib3.exceptions.SubjectAltNameWarning)

**Comment by aroraharsh23** [comment]
Thanks for updating. Will verify the same and update in script.

**Comment by aroraharsh23** [comment]
@rafaelpirolla Can you specify the requests version.
I just installed requests latest : requests-2.23.0
and it did install urllib3-1.25.9

##########
python2.7 -m pip install requests
Collecting requests
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Installing collected packages: urllib3, requests
Successfully installed requests-2.23.0 urllib3-1.25.9
################

**Comment by rafaelpirolla** [comment]
That's the issue. For this version these lines doesn't work:
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
requests.packages.urllib3.disable_warnings(SubjectAltNameWarning)
--
They run without errors but they don't supres the errors thrown if you access an https url with untrusted certificate.

**Comment by aroraharsh23** [comment]
Ok, will update then

**Comment by rafaelpirolla** [comment]
Tricky... I actually could not replicate:
`docker run -it --rm -e http_proxy=http://host.docker.internal:3128 -e https_proxy=http://host.docker.internal:3128 --name came-31 python:2-alpine sh`

`#pip install requests
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 idna-2.9 requests-2.23.0 urllib3-1.25.9`

**Comment by rafaelpirolla** [comment]
I need to set NS_VALIDATE_CERT environment variable to no to have https with verify=False...

**Comment by aroraharsh23** [comment]
By default, there is no cert validation, so if you don't need to set anything. 
if you want to validate then only you need to set NS_VALIDATE_CERT to True and provide certpath. I hope documentation is clear on this.
If you don't want https then just set --secure='no'.
Please note, by default it is 'https' with no cert validation.

**Comment by rafaelpirolla** [comment]
Got it. I still don't know why adding these lines:
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

And removing these:
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

Makes the script start working in my test environment if the test I created in the docker environment works with both options (i.e. doesn't print warnings).

**Comment by aroraharsh23** [comment]
I tested on 2 different Setups, installing requests from scratch(urllib3 is clearly a part of this).
No warnings anywhere. 
Maybe you can try uninstalling and installing requests again(if you haven't done that), or try in a separate system. It should be fine.

**Comment by rafaelpirolla** [comment]
I could reproduce on amazon linux 2 on amazon, not in the container though.

**Comment by rafaelpirolla** [comment]
Ok, there is some package redundancy when installing awscli through system package manager.
Removing from OS using yum and installing everything through pip made it work.
Thanks for all the support.

Anyhow, I believe you should stick to setting up urllib3 as a separate package as they were separated since requests >= 2.16.0 with:
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

**Comment by rafaelpirolla** [comment]
Anyhow I think you could close this one but put some TODO somewhere?

**Comment by aroraharsh23** [comment]
Sure, i would take this into consideration for our next release, which will be on python3, that will require revisiting all pip requirements.
