### ISSUE TITLE
Can we get config endpoints?

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/citrix-adc-metrics-exporter#35]
https://github.com/citrix/citrix-adc-metrics-exporter/blob/942d8ee6dfc132bb7cb14a9d7e9b845b2e3b9420/metrics.json#L360

If you try to reach this as a stat endpoint you get:
{ "errorcode": 1232, "message": "Invalid object name [lbvserver_binding]", "severity": "ERROR" }

Maybe you wanted to add:
["vslbhealth", "lb_members_up_total"]
In the lbvserver block as a gauge?

Kind regards,
Rafael.

**Comment by aroraharsh23** [comment]
@rafaelpirolla 
If you refer the code, for 'lbvserver_binding', we use 'nitro/v1/stat/lbvserver' and get 'actsvcs'

I am not sure, from where did you get above call from our code. 
In general, config entry gets are an avoid, as, in case of large number of entries, it takes more time to fetch data.
Is current implementation not giving you the % up stats ?

**Comment by rafaelpirolla** [comment]
Yeah, just checked, thanks for the clarification.

I assumed you passed everything directly from metric.json to v1/nitro/stat and there is a config endpoint with the same name:
https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/12.1/configuration/load-balancing/lbvserver_binding/lbvserver_binding/
Hence my confusion.
