### ISSUE TITLE
Gauges?

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/citrix-adc-metrics-exporter#38]
https://github.com/citrix/citrix-adc-metrics-exporter/blob/15f435bad8b3bef42367caf4be5b954a9d7b1415/metrics.json#L5

daystoexpiration also?

Shouldn't this be a gauge as it can go down?

**Comment by aroraharsh23** [comment]
To correct:
'disk1avail' is a value, it can go up/down as a counter.. is it not changing?  An entity in 'system' Gauge meant values in percentage terms.

We already have usage Gauges:
 ["disk1perusage", "citrixadc_var_partition_used_percent"],
 ["disk0perusage", "citrixadc_flash_partition_used_percent"]

'disk1avail' percentage is just the remaining of what's used.
Again, 'daystoexpiration' can go up/down as a counter, percentage Gauge is N.A.

Let me know if the understanding is correct or your requirement is different.

**Comment by aroraharsh23** [comment]
Can we close this or still some doubt. here?

**Comment by rafaelpirolla** [comment]
I think that any metric that can go down is a gauge. If you set disk1avail as a prometheus counter some promql functions would miss behave, I think. But you can close this if you want, it's easy to fix it in the client side.
