### ISSUE TITLE
add custom label

### ISSUE THREAD

**Issue by gmounica39** [citrix/citrix-adc-metrics-exporter#43]
Is it possible to add custom label to each metric, for example, the hostname of the netscaler ? 

(We plan on exposing nitroAPI on a different network, so it's not feasible for us to use hostname instead of nsip in the --target-nsip arg)

**Comment by aroraharsh23** [comment]
Is the requirement here to provide custom metric via arg ? Or you are asking for specifically hostname as label for each metric?

**Comment by gmounica39** [comment]
Nevermind, this is no longer needed.

I have one more question though - How frequently does the exporter scrape the metrics out of ADC?
